/******************************************************************************
 *
 * Module: SEVEN SEGMENT
 *
 * File Name: seve_segment.c
 *
 * Description: Source file for the AVR SEVEN SEGMENT driver
 *
 * Author: Ahmed Osama
 *
 *******************************************************************************/


#include "seven_segment.h"
#include "gpio.h"
#include "common_macros.h"
#include <avr/io.h>

void SEVEN_SEGMENT_enable_First()
{
	GPIO_setupPinDirection(SEVEN_SEGMENT_FIRST_ENABLE_PORT_ID,SEVEN_SEGMENT_FIRST_ENABLE_PIN_ID,PIN_OUTPUT);
	GPIO_writePin(SEVEN_SEGMENT_FIRST_ENABLE_PORT_ID,SEVEN_SEGMENT_FIRST_ENABLE_PIN_ID,LOGIC_HIGH);
}
void SEVEN_SEGMENT_disable_First()
{
	GPIO_writePin(SEVEN_SEGMENT_FIRST_ENABLE_PORT_ID,SEVEN_SEGMENT_FIRST_ENABLE_PIN_ID,LOGIC_LOW);
}
#if(NUMBER_OF_SEVEN_SEGMENT==2)

void SEVEN_SEGMENT_enable_Second()
{
	GPIO_setupPinDirection(SEVEN_SEGMENT_SECOND_ENABLE_PORT_ID,SEVEN_SEGMENT_SECOND_ENABLE_PIN_ID,PIN_OUTPUT);
	GPIO_writePin(SEVEN_SEGMENT_SECOND_ENABLE_PORT_ID,SEVEN_SEGMENT_SECOND_ENABLE_PIN_ID,LOGIC_HIGH);
}
void SEVEN_SEGMENT_disable_Second()
{
	GPIO_writePin(SEVEN_SEGMENT_SECOND_ENABLE_PORT_ID,SEVEN_SEGMENT_SECOND_ENABLE_PIN_ID,LOGIC_LOW);
}

#endif
void SEVEN_SEGMENT_init()
{
	
#if(DECODER == FALSE)
	uint8 i;
	for(i=0;i<7;i++)
	{
		GPIO_setupPinDirection(SEVEN_SEGMENT_PORT_ID, SEVEN_SEGMENT_PIN_ID+i,PIN_OUTPUT);
	}

#elif(DECODER == TRUE)

	GPIO_setupPinDirection(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID,PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+1,PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+2,PIN_OUTPUT);
	GPIO_setupPinDirection(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+3,PIN_OUTPUT);

#endif

}
void SEVEN_SEGMENT_display_First(uint8 value)
{

	value=value%10;
	
#if(DECODER == TRUE)
	
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID,(GET_BIT(value,0)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+1,(GET_BIT(value,1)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+2,(GET_BIT(value,2)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+3,(GET_BIT(value,3)));

#elif(DECODER == FALSE)
	
	switch(value)
	{
	case 0:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 2:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 3:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 4:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 5:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 6:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 7:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 8:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	}
#endif

}
#if(NUMBER_OF_SEVEN_SEGMENT==2)

void SEVEN_SEGMENT_display_Second(uint8 value)
{
	
	value/=10;
	
#if(DECODER == TRUE)

	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID,(GET_BIT(value,0)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+1,(GET_BIT(value,1)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+2,(GET_BIT(value,2)));
	GPIO_writePin(SEVEN_SEGMENT_DECODER_PORT_ID,SEVEN_SEGMENT_DECODER_PIN_ID+3,(GET_BIT(value,3)));

#elif(DECODER == FALSE)

	switch(value)
	{
	case 0:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 1:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 2:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 3:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 4:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 5:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 6:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 7:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_LOW);
		break;
	case 8:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	case 9:
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+1,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+2,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+3,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+4,LOGIC_LOW);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+5,LOGIC_HIGH);
		GPIO_writePin(SEVEN_SEGMENT_PORT_ID,SEVEN_SEGMENT_PIN_ID+6,LOGIC_HIGH);
		break;
	}
	
#endif
	
}


#endif


